name: SIEAHungerGames
main: me.Zachary_Peculier.SIEAHungerGames.HungerGames
author: Zachary_Peculier and endoffile
version: 1.4
commands:
  start:
    description: countdown
    usage: /<command> <args>
  alive:
    description: Lists players in game
    usage: /<command>
  who:
    description: Lists players in game
    usage: /<command>
  help:
    description: gives information
    usage: /<command>
  admin:
    description: admin mode
    usage: /<command>
  say:
    description: Broadcast message
    usage: /<command>
permissions:
  siea.admin:
     description: Admin perms
     default: op
