name: SIEAHungerGames
main: me.Zachary_Peculier.SIEAHungerGames.core
author: Zachary_Peculier and endoffile
version: 1.2
commands:
  start:
    description: countdown
    usage: /<command> <args>
  join:
    description: joins game
    usage: /<command>
  leave:
    description: leave game
    usage: /<command>
  alive:
    description: Lists players in game
    usage: /<command>
