name: SIEAHungerGames
main: me.Zachary_Peculier.SIEAHungerGames.core
author: Zachary_Peculier and endoffile
version: 1.2
commands:
  start:
    description: countdown
    usage: /<command> <args>
  alive:
    description: Lists players in game
    usage: /<command>
  who:
    description: Lists players in game
    usage: /<command>
  help:
    description: gives information
    usage: /<command>
  magicmabis:
    description: admin mode
    usage: /<command>